### PR TITLE
Bugfix/animation grades and badge coverage!

### PR DESCRIPTION
**Pull request by apomalyn**
Two things in this PR:

1. I did some refactoring inside the CI to get a coverage badge and put the steps related to the coverage inside their own job.
2. I added an animation for the grades pages when the list is build for the first time @zaclimon this is for you :wink: 

https://user-images.githubusercontent.com/22211097/122500316-94ad7c00-cfc0-11eb-9e49-9a172138b550.mp4

### CODE REVIEW

**Comment by camillebrulotte** [comment]
> Two things in this PR:
> 
> 1. I did some refactoring inside the CI to get a coverage badge and put the steps related to the coverage inside their own job.
> 2. I added an animation for the grades pages when the list is build for the first time @zaclimon this is for you 😉
> 
>  screen-20210617-230303.mp4

Ouhh j'aime ça j'aime ça

**Comment by apomalyn** [comment]
And there we go: Coverage Badge

@AlexandreMarkus for you my friend :smile: :tada:

**Review by AlexandreMarkus — APPROVED** [review]
Coverage badge!!!!!

**Review by MysticFragilist — APPROVED** [review]
LGTM 🍾 😄

**Pull request merged**
