### PR TITLE
#696 Change invalid credentials on sign in error message

### PR DESCRIPTION
**Pull request by EffBureau**
### ⁉️ Related Issue
#696 Change error message if login is invalid.

## 📖 Description
I added a new error string in I10n for invalid credentials. Mentioned in the error message that it could be a server error as there is no way currently to know if the error is really the credentials or if we could not reach the server.

Removed multiple strings that were not used in the application.

Removed the universal code matcher as there is no way for a user to enter anything other than the regex for the universal code. I removed this part of the code because telling the user their username is invalid is too specific and opens us up to security breaches. It is best to say something like "username and password are invalid" rather than "your username is invalid".

Changed the error message for invalid credentials. It should be noted that displaying a toast as the error message greatly limits the number of characters that can be displayed in the message.

Modified tests to reflect changes made

### 🧪 How Has This Been Tested?
I executed the appropriate tests and all passed.

I tested manually to see if the message was displayed correctly.

### ☑️ Checklist before requesting a review
- [x] I have performed a self-review of my code.
- [n/a] If it is a core feature, I have added thorough tests.
- [n/a] If needed, I added analytics.
- [x] Make sure to add either one of the following labels: `version: Major`,`version: Minor` or `version: Patch`. 
- [n/a] Make sure golden files changes were reviewed and approved.

### 🖼️ Screenshots (if useful):
image

### CODE REVIEW

**Comment by EffBureau** [comment]
I added the patch label and the job still fails

**Comment by XavierPaquet-Rapold** [comment]
The universal code matcher was added to reduce the number of people asking questions about how to connect to their account. The message guides the user toward using their universal code instead of their email address or permanent code.
I think the security concern is valid, but since it's only a format validation and not a connexion error message, the risk is reduced. The validation also reduces the number of emails received because of connexion errors.
I'm open to talk more about it if you'd like.

**Comment by EffBureau** [comment]
> The validation also reduces the number of emails received because of connexion errors.

Less work is always better! 😉

Since the format of the universal code is available publicly, you are right that there is less risk as any hacker worth their salt will be able to find that information. I will remove those changes.

**Review by XavierPaquet-Rapold — APPROVED** [review]
LGTM :fire:

**Review by MysticFragilist — APPROVED** [review]
LGTM! 🔥 💯

**Pull request merged**
