### PR TITLE
Fix typo semester instead of session

### LINKED ISSUE #408: 'Session' should be 'Semester'
**Describe the issue** 
```"session progress" doit être plutôt "semester progress" parce que "session" en anglais veut dire une séance.```

**Screenshot** 
screenshot

**Device Infos** 
- **Device:** BE2026 
- **Version:** 4.9.1 
- **Connectivity:** ConnectivityResult.mobile 
- **Build number:** 1645466811 
- **Platform operating system:** android 
- **Platform operating system version:** BE2026_17_211229

### PR DESCRIPTION
**Pull request by MysticFragilist**
Pretty descriptive, would fix any typo made in the UI. :)

closes #408

### CODE REVIEW

**Review by eneiss — APPROVED** [review]
LGTM 👌

**Review by AlexandreMarkus — APPROVED** [review]

**Comment by apomalyn** [comment]
@MysticFragilist you need to update the goldens :)

**Review by AlexandreMarkus — APPROVED** [review]
LGTM!!

**Review by camillebrulotte — APPROVED** [review]
LGTM

**Pull request merged**
