### PR TITLE
Feature/week calendar events

### LINKED ISSUE #211: [Schedule] Add a view to see the complete schedule weekly
**Describe the issue** 
```est-il possible d’avoir un bouton pour avoir l’horaire d’une semaine au complet?```

**Screenshot** 
screenshot

**Device Infos** 
- **Version:** 4.2.3 
- **Connectivity:** ConnectivityResult.wifi 
- **Build number:** 1631981526 
- **Platform operating system:** ios 
- **Platform operating system version:** 14.7.1

### PR DESCRIPTION
**Pull request by JonathanDuvalV**
Closes #211 

<details>
 <summary>Week events calendar</summary>
 <video src="https://user-images.githubusercontent.com/45638733/150627038-dc8b6aa7-2226-4914-b88b-007f55763142.mp4">
</details>

### CODE REVIEW

**Comment by apomalyn** [comment]
If I may :sweat_smile: the toggle button should be on the settings of the schedule instead of the AppBar.
In the AppBar there is no text or indicator that explain what the toggle button does, so I think it's a little confusing to only have a toggle button. What do you think?

**Comment by JonathanDuvalV** [comment]
> If I may 😅 the toggle button should be on the settings of the schedule instead of the AppBar. In the AppBar there is no text or indicator that explain what the toggle button does, so I think it's a little confusing to only have a toggle button. What do you think?

At first it was in the settings, as I showed in the issue before https://github.com/ApplETS/Notre-Dame/issues/211#issuecomment-951096828. But was told to move it during one of the coding sessions. Did I misunderstood where to move it to?

**Comment by JonathanDuvalV** [comment]
> > If I may 😅 the toggle button should be on the settings of the schedule instead of the AppBar. In the AppBar there is no text or indicator that explain what the toggle button does, so I think it's a little confusing to only have a toggle button. What do you think?
> 
> At first it was in the settings, as I showed in the issue before [#211 (comment)](https://github.com/ApplETS/Notre-Dame/issues/211#issuecomment-951096828). But was told to move it. Did I misunderstood where to move it to?

**Comment by apomalyn** [comment]
@JonathanDuvalV I'm sorry. This is my mistake after seeing it, without any explanation or indication I don't understand the purpose of the button...but it's only my opinion (and really sorry to have changed it --') so this could be discussed with the rest of the club :smile:

**Comment by JonathanDuvalV** [comment]
@apomalyn No worries 😄 and good idea I'll show the current UI to the rest of the club during the next coding session and see what they think about it. I'll adjust it afterwards

**Comment by camillebrulotte** [comment]
C'est tu ben ben compliquer le mettre dans les settings ? 😂😅 C'est pas si pire ça le fait ! Mais ça fait beaucoup de petit bouton en haut je crois c'est surtout ça

**Comment by JonathanDuvalV** [comment]
My bad I just saw the answer 😅 I'll move it back to settings in the next few days!

**Comment by JonathanDuvalV** [comment]
I moved everything back to settings 😄

**Review by apomalyn — APPROVED** [review]
LGTM! I can't test it but the code looks good 😄

**Review by MysticFragilist — APPROVED** [review]
LGTM! 💯

**Pull request merged**
