### PR TITLE
Add credits to course details page

### LINKED ISSUE #575: Issue from ÉTS Mobile
**Describe the issue** 
```i can’t get access to my schedule ```

**Screenshot** 
screenshot

**Device Infos** 
- **Device:** iPhone10,6 
- **Version:** 4.9.1 
- **Connectivity:** ConnectivityResult.mobile 
- **Build number:** 1645469727 
- **Platform operating system:** ios 
- **Platform operating system version:** Version 15.6.1 (Build 19G82)

### PR DESCRIPTION
**Pull request by camillebrulotte**
### ⁉️ Related Issue

We could not know how many credits is a course.

## 📖 Description
Show the number of credits a course is.

### 🧪 How Has This Been Tested?
Launch the application and go to the grades page. Then click on one of the courses.

### ☑️ Checklist before requesting a review
- [x] I have performed a self-review of my code.
- [x] If it is a core feature, I have added thorough tests.
- [x] If needed, I added analytics.
- [x] Make sure to add either one of the following labels: `version: Major`,`version: Minor` or `version: Patch`. 
- [x] Make sure golden files changes were reviewed and approved.

### 🖼️ Screenshots (if useful):
image

Closes #575

### CODE REVIEW

**Review by Udito3 — DISMISSED** [review]
LGTM 😁

**Review by XavierPaquet-Rapold — APPROVED** [review]
LGTM

**Review by eneiss — APPROVED** [review]
LGTM 💯

**Review by Udito3 — APPROVED** [review]
LGTM! 🔥

**Review by Udito3 — APPROVED** [review]
LGTM!!

**Review by MysticFragilist — APPROVED** [review]
LGTM! 💳

**Pull request merged**
