### PR TITLE
Feature/timeline api ios

### PR DESCRIPTION
**Pull request by JonathanDuvalV**
## 📖 Description
The SignetsAPI is now implemented in Swift. The API calls to Signets are done through the widget instead of using the UserDefaults' values (cache).

### ☑️ Checklist before requesting a review
- [x] I have performed a self-review of my code.
- [ ] If it is a core feature, I have added thorough tests.
- [x] If needed, I added analytics.
- [x] Make sure to add either one of the following labels: `version: Major`,`version: Minor` or `version: Patch`. 
- [x] Make sure golden files changes were reviewed and approved.

### CODE REVIEW

**Review by AntoineLemelin — APPROVED** [review]
LGTM!

**Comment by JonathanDuvalV** [comment]
ogo voulait une photo

image

**Review by AntoineLemelin — APPROVED** [review]
LGTM!

**Review by MysticFragilist — APPROVED** [review]
LGTM!

**Pull request merged**
