### PR TITLE
BugFix #663 Prevent the submit button from sending github issues mult…

### PR DESCRIPTION
**Pull request by Anthony-karabian**
…iple times when user clicks the button multiple times.

## 📖 Description
I've added a boolean to capture the state of the code being executed that pushes the issue to github. Since the button submit itself is in the BetterFeedback package i couldn't modify code inside it. 

### 🧪 How Has This Been Tested?
I tested by printing out in the terminal command and testing if clicking the button multiple times only prints out once. 

### ☑️ Checklist before requesting a review
- [x] I have performed a self-review of my code.
- [x] If it is a core feature, I have added thorough tests.
- [x] Do we need to implement analytics?
- [x] Make sure to add either one of the following labels: `version: Major`,`version: Minor` or `version: Patch`.

### CODE REVIEW

**Review by HugoMigner — DISMISSED** [review]
LGTM 🔥

**Review by MysticFragilist — APPROVED** [review]
LGTM! 💯 Good job sur ta première PR :)

**Review by MysticFragilist — CHANGES_REQUESTED** [review]
J'viens de voir des probs de tests aussi, à fixer avant :)

**Review by MysticFragilist — DISMISSED** [review]
LGTM! :100:

**Review by XavierPaquet-Rapold — APPROVED** [review]
LGTM

**Review by MysticFragilist — DISMISSED** [review]

**Review by camillebrulotte — APPROVED** [review]
LGTM

**Review by MysticFragilist — APPROVED** [review]

**Review by MysticFragilist — CHANGES_REQUESTED** [review]
Je viens de voir though que ton flutter analyze finit avec des erreurs, ils faudraient les fix avant!: image

**Comment by Anthony-karabian** [comment]
> Je viens de voir though que ton flutter analyze finit avec des erreurs, ils faudraient les fix avant!: image
Bizzare de mon cote, mon ide me dit que je doit import `dart:typed_data` sinon j'ai une erreur.

**Comment by Anthony-karabian** [comment]
> Je viens de voir though que ton flutter analyze finit avec des erreurs, ils faudraient les fix avant!: image

DONE

**Review by MysticFragilist — APPROVED** [review]

**Review by XavierPaquet-Rapold — APPROVED** [review]
LGTM 💯

**Review by AntoineLemelin — APPROVED** [review]
LGTM

**Pull request merged**
