### PR TITLE
Fix build for Flutter 3.0.0 and above

### LINKED ISSUE #467: Project no longer building with Flutter 3.0.0+
**Describe the bug**
The project does not build on Android (and maybe on iOS too) with Flutter 3.0.0 and above since the addition of home widgets.

**To Reproduce**
1. Make sure you're on the master branch of the repository and using Flutter 3.0.0 or above
2. `flutter build apk` 

**Expected behavior**
The project should build.

**Additional context**

<details>  
<summary>Error thrown while building (with verbose)</summary>

```
[   +1 ms] > Task :flutter_config:compileReleaseSources
[        ] > Task :home_widget:compileReleaseKotlin FAILED
[   +1 ms] e:
D:\Flutter\flutter_windows_1.22.6-stable\flutter\.pub-cache\hosted\pub.dartlang.org\home_widget-0.1.5\android\src\main\kotlin\es\antonborri\home_widget\HomeWidgetPlugin.kt: (19, 1):
Class 'HomeWidgetPlugin' is not abstract and does not implement abstract member public abstract fun onNewIntent(p0: Intent): Boolean defined in
io.flutter.plugin.common.PluginRegistry.NewIntentListener
[   +4 ms] e:
D:\Flutter\flutter_windows_1.22.6-stable\flutter\.pub-cache\hosted\pub.dartlang.org\home_widget-0.1.5\android\src\main\kotlin\es\antonborri\home_widget\HomeWidgetPlugin.kt: (193, 5):
'onNewIntent' overrides nothing
[+2995 ms] > Task :device_info_plus:verifyReleaseResources
[   +1 ms] > Task :connectivity_plus:verifyReleaseResources
[        ] > Task :firebase_analytics:verifyReleaseResources
[ +386 ms] > Task :firebase_crashlytics:mergeReleaseResources
[ +500 ms] > Task :firebase_core:mergeReleaseResources
[   +1 ms] > Task :flutter_config:mergeReleaseResources
[+3402 ms] > Task :app:compileFlutterBuildRelease
[  +93 ms] FAILURE: Build failed with an exception.
[   +2 ms] * What went wrong:
[   +1 ms] Execution failed for task ':home_widget:compileReleaseKotlin'.
[   +1 ms] > A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
[   +1 ms]    > Compilation error. See log for more details
[   +1 ms] * Try:
[   +1 ms] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
[   +1 ms] * Get more help at https://help.gradle.org
[   +1 ms] BUILD FAILED in 21s
```
</details>

It seems to be an issue with the home_widget package that has been fixed in version 0.1.6 of (see https://github.com/ABausG/home_widget/issues/83). Using the latest version should work fine (it did work for me).

### PR DESCRIPTION
**Pull request by eneiss**
Closes #467 

This should fix the build error that happens with Flutter 3 and home_widget prior to 0.1.6.

### CODE REVIEW

**Review by MysticFragilist — APPROVED** [review]
LGTM!

**Review by camillebrulotte — APPROVED** [review]
LGTM ? :D Ahahahha

**Review by MysticFragilist — APPROVED** [review]
LGTM! 🚀

**Review by HugoMigner — APPROVED** [review]
LGTM! 👀

**Pull request merged**
