### PR TITLE
Fix bug/enhancement report

### LINKED ISSUE #798: Wrong label and 'email' not properly formatted when reporting a bug/enhancement
**Describe the bug**
'Email' in a bug report should not look like that and the label should be 'bug' or 'enhancement'.

**Screenshots**
image

### PR DESCRIPTION
**Pull request by camillebrulotte**
### ⁉️ Related Issue
CLoses #798

## 📖 Description
Change the 'email' format and fix the label

### 🧪 How Has This Been Tested?
N/A

### ☑️ Checklist before requesting a review
- [x] I have performed a self-review of my code.
- [x] If it is a core feature, I have added thorough tests.
- [x] If needed, I added analytics.
- [x] Make sure to add either one of the following labels: `version: Major`,`version: Minor` or `version: Patch`. 
- [x] Make sure golden files changes were reviewed and approved.

### 🖼️ Screenshots (if useful):
N/A

### CODE REVIEW

**Review by Udito3 — APPROVED** [review]
LGTM 😁

**Comment by JonathanDuvalV** [comment]
LGTM 🥳

**Review by JonathanDuvalV — APPROVED** [review]
LGTM 🥳

**Comment by HugoMigner** [comment]
LGTM 🥵🌵🎉

**Pull request merged**
