### PR TITLE
Add custom widget for event tile in calendar schedule view

### LINKED ISSUE #781: Create a custom event tile for the Schedule Calendar
**Is your feature request related to a problem? Please describe.**

The default tile that currently shows your classes in the schedule calendar has a lot of limitations (visuals, string formatting, etc). However, the calendar offers the option to use your own component as an event tile, which would solve most problems mentioned before.

**Describe the solution you'd like**

Create and implement a new tile that shows your classes in the schedule calendar.

**Useful content**
[Flutter package for auto-resizing text](https://pub.dev/packages/auto_size_text)

### PR DESCRIPTION
**Pull request by HugoMigner**
### ⁉️ Related Issue
Closes #781 

## 📖 Description
This PR changes the built-in event tile in the calendar view to a custom made tile, allowing for easier maintainability. The tile also now has an onTap event to show a modal with the class information.

### 🧪 How Has This Been Tested?
Existing tests have been modified to implement the new information required for the custom tiles.

### ☑️ Checklist before requesting a review
- [ x ] I have performed a self-review of my code.
- [ x ] If it is a core feature, I have added thorough tests.
- [ x ] If needed, I added analytics.
- [ x ] Make sure to add either one of the following labels: `version: Major`,`version: Minor` or `version: Patch`. 
- [ x ] Make sure golden files changes were reviewed and approved.

### 🖼️ Screenshots (if useful):
image
image

### CODE REVIEW

**Review by MysticFragilist — APPROVED** [review]
LGTM! 🔥

**Review by eneiss — APPROVED** [review]
LGTM ! Minor edit suggested but it's no big deal at all 😁 
Good job 🔥

**Review by eneiss — APPROVED** [review]
LGTM :)

**Review by XavierPaquet-Rapold — APPROVED** [review]
LGTM 🔥

**Pull request merged**
