### PR TITLE
Upgrade dependencies

### PR DESCRIPTION
**Pull request by apomalyn**
This PR upgrade almost every dependency (except `percent_indicator` which could be in 4.0.0 but I didn't have the time to fix the breaking changes 😅 ).

This PR is linked with the [null safety PR of ETS-API-Clients](https://github.com/ApplETS/ETS-API-Clients/pull/3) so please do not merge it yet (well the CI is going to fail because the 0.5.0 of the package isn't available yet).

### CODE REVIEW

**Review by MysticFragilist — APPROVED** [review]
LGTM! 🚀

**Review by MysticFragilist — APPROVED** [review]
LGTM! 🥇

**Review by MysticFragilist — APPROVED** [review]

**Comment by apomalyn** [comment]
@MysticFragilist seems like the pr-size-labeler isn't working ? 🤔

**Review by camillebrulotte — APPROVED** [review]
LGTM :D

**Review by AlexandreMarkus — APPROVED** [review]
LGTM!

**Pull request merged**
