### PR TITLE
Update gradle plugin

### LINKED ISSUE #251: Update the Android Gradle plugin
**Is your feature request related to a problem? Please describe.**
I would like to update the Android Gradle plugin to the latest version. Also, JCenter is now deprecated.

**Describe the solution you'd like**
https://developer.android.com/studio/releases/gradle-plugin
https://developer.android.com/studio/build/optimize-your-build
https://developer.android.com/studio/build/jcenter-migration
https://blog.gradle.org/jcenter-shutdown

### PR DESCRIPTION
**Pull request by AlexandreMarkus**
* Updated Android Gradle plugin to the latest version
* Build speed should be better 
* JCenter deprecated dependency removed
* removed unnecessary intl plugin since localizations are generated by Flutter SDK itself

Closes #251 

https://developer.android.com/studio/releases/gradle-plugin
https://developer.android.com/studio/build/optimize-your-build
https://developer.android.com/studio/build/jcenter-migration
https://blog.gradle.org/jcenter-shutdown

### CODE REVIEW

**Comment by MysticFragilist** [comment]
Yea I think @apomalyn mention this to me yesterday, since the PR that obfuscated the release, the logs are all getting saved under a file name zEa.java :
image
I don't know if it's an actual error that are getting badly logged or if it's just the firebase crashlytics that are logging an error on itself:
```
Non-fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError: type '_OneByteString' is not a subtype of type 'bool?' in type cast. Error thrown null.
       at zEa.PZb(zEa.java:89)
       at Mua.PZb(Mua.java:52)
       at dva.SWe(dva.java:137)
```

**Review by apomalyn — DISMISSED** [review]
LGTM 🚀

**Review by MysticFragilist — DISMISSED** [review]
I just added a comment to @apomalyn previous comment, but if it was cleared out you can merge this :smile:

**Comment by AlexandreMarkus** [comment]
@MysticFragilist @apomalyn I just did a FirebaseCrashlytics.crash(), can you please validate you just received it and this PR will be ready to go !!

**Comment by MysticFragilist** [comment]
Did you find it @apomalyn ? what's your phone @AlexandreMarkus? I can filter by device

**Review by MysticFragilist — APPROVED** [review]
Nevermind found it, it works!! LGTM :smile:

**Pull request merged**
