### PR TITLE
Remove blue color for emergency procedures

### LINKED ISSUE #56: Emergency procedures webview doesn't follow the theme
**Describe the bug**
The theme of the webview in emergency follow the phone theme instead of the one from the app.
The list of emergency procedures should be white or black depending on the theme

**To Reproduce**
1. Go to ETS
2. Click on Security
3. Scroll down to Emergency procedures
4. Click on one item

**Expected behavior**
Webview should follow the theme of the app and not the theme of the phone.
Emergency procedures should not be blue.

**Screenshots**
image
image

### PR DESCRIPTION
**Pull request by MysticFragilist**
Fixed by swapping the TextButton to a Card widget.
dark theme:
<image src="https://user-images.githubusercontent.com/25663435/111914046-d91f8f00-8a46-11eb-8ac7-54302aa9886f.png" width="200"/>
light theme:
<image src="https://user-images.githubusercontent.com/25663435/111914055-e5a3e780-8a46-11eb-8f76-438457203333.png" width="200"/>

closes #56

### CODE REVIEW

**Review by AlexandreMarkus — CHANGES_REQUESTED** [review]
Nice!! I would add some padding on the left of the texts

**Review by apomalyn — COMMENTED** [review]
Same comment as @AlexandreMarkus some left padding on the card text and that would be good!

**Comment by MysticFragilist** [comment]
This is what I just pushed:
<image src="https://user-images.githubusercontent.com/25663435/112047463-b616dd00-8b23-11eb-8d57-dd3ddd122370.png" width="200"/>
I tried aligning it with the phone icon. I'm not sure if it's me but it seems that the two phone are not align (I think it's because one is in a card and the other not). What do you guys think about putting the extension also in a card to follow the layout of the page. Example:
<image src="https://user-images.githubusercontent.com/25663435/112048672-09d5f600-8b25-11eb-9c2c-90127a188442.png" width="200"/>
It won't be clickable though

**Comment by AlexandreMarkus** [comment]
Great for the padding! I would leave the extension as it was before since if it is a card, the user will try to click on it and will think it is not working

**Comment by MysticFragilist** [comment]
> Great for the padding! I would leave the extension as it was before since if it is a card, the user will try to click on it and will think it is not working

Okayy yes, didn't think of that! I will still put it in a card to have the right alignment but I'll make the card transparent so it doesn't feel buttony.

<image src="https://user-images.githubusercontent.com/25663435/112054049-781db700-8b2b-11eb-8858-992b00f29c43.png" width="200"/>

Does this work @AlexandreMarkus ?

**Comment by AlexandreMarkus** [comment]
> > Great for the padding! I would leave the extension as it was before since if it is a card, the user will try to click on it and will think it is not working
> 
> Okayy yes, didn't think of that! I will still put it in a card to have the right alignment but I'll make the card transparent so it doesn't feel buttony.
> 
> <image src="https://user-images.githubusercontent.com/25663435/112054049-781db700-8b2b-11eb-8858-992b00f29c43.png" width="200"/>
> 
> Does this work @AlexandreMarkus ?

Excellent idea!!!

**Review by apomalyn — APPROVED** [review]
LGTM !! :tada: :champagne:

**Pull request merged**
