### PR TITLE
Bugfix/fix duplicate course in dashboard

### PR DESCRIPTION
**Pull request by XavierPaquet-Rapold**
### ⁉️ Related Issue
closes: #510 

## 📖 Description
- Create an index for the displayed view. If displayed, the bottom bar will not update the view.
- Make the dashboard view refreshable

### 🧪 How Has This Been Tested?

1. Click multiple times on the same icon on the bottom bar the see that the page is not updating
2. Click on all bottom bar icons to see that they change
3. Refresh the dashboard view by swipping down the page

### ☑️ Checklist before requesting a review
- [x] I have performed a self-review of my code.
- [x] If it is a core feature, I have added thorough tests.
- [x] Do we need to implement analytics?
- [x] Make sure to add either one of the following labels: `version: Major`,`version: Minor` or `version: Patch`. 
- [x] Make sure golden files changes were reviewed and approved.

### CODE REVIEW

**Review by camillebrulotte — APPROVED** [review]
LGTM ! :D

**Review by MysticFragilist — DISMISSED** [review]
LGTM! :fire:

**Review by camillebrulotte — APPROVED** [review]
LGTM !

**Review by eneiss — APPROVED** [review]
LGTM 🔥

**Pull request merged**
