### PR TITLE
Fix Hero Animation

### PR DESCRIPTION
**Pull request by ZanderLavastory**
### ⁉️ Related Issue

closes: #232 

## 📖 Description

The animation for opening and closing grade details page has been changed. When opening the grade details page, the page now slides from the bottom. When closing the grade details page, the screen no longer flashes red. 

### 🧪 How Has This Been Tested?

Navigate to the "Student" page, and open one of the grades. Then close the grade. Observe the animations.

### ☑️ Checklist before requesting a review
- [x] I have performed a self-review of my code.
- [ ] If it is a core feature, I have added thorough tests.
- [ ] Do we need to implement analytics?
- [x] Make sure to add either one of the following labels: `version: Major`,`version: Minor` or `version: Patch`. 

### 🖼️ Screenshots (if useful):

Before:
https://user-images.githubusercontent.com/64044057/194782512-78ff55af-651e-4b98-a568-f4afb97d06e9.mp4

After:
https://user-images.githubusercontent.com/64044057/194782516-e5f9d7ea-0384-4aa5-96e3-33d6c897befb.mp4

### CODE REVIEW

**Comment by MysticFragilist** [comment]
@ZanderLavastory Scuse :sweat_smile: je viens de me rendre compte que le tag je t'ai dit de mettre en commit est pas le bon c'est `[CI UPDATE GOLDENS]` sans _

**Comment by ZanderLavastory** [comment]
>

**Comment by ZanderLavastory** [comment]
> Pas de problème, je vais l'essayer sans les _

**Comment by MysticFragilist** [comment]
@ZanderLavastory On va faire un merge pour les goldens files, on attendra pour cette PR là avant que la 694 soit merger.

**Review by MysticFragilist — APPROVED** [review]

**Review by eneiss — APPROVED** [review]
LGTM! Good job 🚀

**Review by MysticFragilist — DISMISSED** [review]

**Pull request closed without merging**
