### PR TITLE
Modified procedure to extract env variables and decrypt files

### PR DESCRIPTION
**Pull request by MysticFragilist**
There was an error while installing the repo on @xeniya-nalivaiko computer. I redid on my computer the steps in `README.md` and this was in fact an error (On windows at least).

Basically, the script `env_variables.sh` when executed, exported 2 variables, but the scope of those variables were only inside the file itself. So when the scripts finished the variables weren't exported in the sh session and they were empty when red from `./scripts/decrypt.sh`

So an easy workaround was to call directly `./scripts/decrypt.sh` from the `env_variables.sh` so it is easier for newcomers to install. I modified the procedure in readme, added the new line in the google drive env_var file and did a PR to discuss the changes, I don't know if there is a better way to handle this. Let me know!

### CODE REVIEW

**Review by apomalyn — DISMISSED** [review]
LGTM

**Review by camillebrulotte — APPROVED** [review]
lgtm :D

**Review by AlexandreMarkus — CHANGES_REQUESTED** [review]
Should be done on the French version too ;)

**Comment by apomalyn** [comment]
@AlexandreMarkus  I updated the french version 😄

**Review by apomalyn — APPROVED** [review]
LGTM

**Review by AlexandreMarkus — APPROVED** [review]
LGTM!

**Comment by MysticFragilist** [comment]
Thanks Xavier! 😄

**Pull request merged**
